<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'think\\worker\\' => array($vendorDir . '/topthink/think-worker/src'),
    'think\\composer\\' => array($vendorDir . '/topthink/think-installer/src'),
    'kartik\\plugins\\fileinput\\' => array($vendorDir . '/kartik-v/bootstrap-fileinput'),
    'Workerman\\' => array($vendorDir . '/workerman/workerman'),
    'Smallsha\\' => array($vendorDir . '/ak_smallsha/application/src'),
    'GatewayWorker\\' => array($vendorDir . '/workerman/gateway-worker/src'),
);
