<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit80d5502dd9befe30cff54b15a5cd9af8
{
    public static $files = array (
        'ae1bf0a1bc08e4395058ce04476f374b' => __DIR__ . '/..' . '/ak_smallsha/application/Func.php',
        'ffc1d7141d4fcbaeb47a6929f0811ed1' => __DIR__ . '/..' . '/topthink/think-worker/src/command.php',
    );

    public static $prefixLengthsPsr4 = array (
        't' => 
        array (
            'think\\worker\\' => 13,
            'think\\composer\\' => 15,
        ),
        'k' => 
        array (
            'kartik\\plugins\\fileinput\\' => 25,
        ),
        'W' => 
        array (
            'Workerman\\' => 10,
        ),
        'S' => 
        array (
            'Smallsha\\' => 9,
        ),
        'G' => 
        array (
            'GatewayWorker\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'think\\worker\\' => 
        array (
            0 => __DIR__ . '/..' . '/topthink/think-worker/src',
        ),
        'think\\composer\\' => 
        array (
            0 => __DIR__ . '/..' . '/topthink/think-installer/src',
        ),
        'kartik\\plugins\\fileinput\\' => 
        array (
            0 => __DIR__ . '/..' . '/kartik-v/bootstrap-fileinput',
        ),
        'Workerman\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/workerman',
        ),
        'Smallsha\\' => 
        array (
            0 => __DIR__ . '/..' . '/ak_smallsha/application/src',
        ),
        'GatewayWorker\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/gateway-worker/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit80d5502dd9befe30cff54b15a5cd9af8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit80d5502dd9befe30cff54b15a5cd9af8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
